Upgrade to Stackage LTS Haskell 10.7 (#240)
* Upgrade to Stackage LTS Haskell 10.7

* Fix broken build on Windows

> Error: While constructing the build plan, the following exceptions were encountered:
> In the dependencies for turtle-1.4.5:
>     Win32-2.5.4.1 from stack configuration does not match >=2.2.0.1 && <2.4 (latest matching version
>                   is 2.3.1.1)
> needed due to nirum-0.3.0 -> turtle-1.4.5
> Some potential ways to resolve this:
>   * Recommended action: try adding the following to your extra-deps
>     in C:\projects\nirum-k5n5y\stack.yaml:
> - Win32-2.3.1.1
>   * Set 'allow-newer: true' to ignore all version constraints and build anyway.
>   * You may also want to try using the 'stack solver' command.
> Plan construction failed.

[changelog skip]